import {Store} from './store';

export const AlternateDe: Store = {
  currency: '€',
  labels: {
    inStock: {
      container: '.add-to-cart.details-cart-button.btn.btn-primary.btn-lg.d-flex.justify-content-center.tp-button.btn-season',
      text: ['In den Warenkorb','Vorbestellen'],
    },
    maxPrice: {
      container: '#tle-details-price-section > div.col.campaign-timer-price-section > div > div:nth-child(1) > span.price',
      euroFormat: true,
    },
    outOfStock: [
      {
        container: 'span.d-flex > b:nth-child(1)',
        text: ['liefertermin unbekannt'],
      },
      {
        container: 'span.d-flex > b:nth-child(1)',
        text: ['Artikel kann nicht gekauft werden'],
      },
      {
        container: 'div.col-12 > div:nth-child(1)',
        text: ['Artikel kann derzeit nicht gekauft werden'],
      },
    ],
  },
  name: 'alternate-de',
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.alternate.de/html/product/1898270'
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/MSI/GeForce-RTX-5080-GAMING-TRIO-OC-WHITE-Grafikkarte/html/product/100107958',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/GIGABYTE/GeForce-RTX-5080-GAMING-OC-16G-Grafikkarte/html/product/100108947',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/GIGABYTE/GeForce-RTX-5080-AERO-OC-SFF-16G-Grafikkarte/html/product/100108948',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/ASUS/GeForce-RTX-5080-TUF-ROG-ASTRAL-GAMING-OC-Grafikkarte/html/product/100108199',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/MSI/GeForce-RTX-5080-SUPRIM-SOC-Grafikkarte/html/product/100107953',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/Gainward/GeForce-RTX-5080-Phoenix-Grafikkarte/html/product/100105333',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/GIGABYTE/GeForce-RTX-5080-WINDFORCE-OC-SFF-16G-Grafikkarte/html/product/100108949',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/ZOTAC/GeForce-RTX-5080-SOLID-Grafikkarte/html/product/100108005',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/ZOTAC/GeForce-RTX-5080-SOLID-OC-Grafikkarte/html/product/100108003',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/MSI/GeForce-RTX-5080-VENTUS-3X-OC-PLUS-Grafikkarte/html/product/100107973',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/MSI/GeForce-RTX-5080-GAMING-TRIO-OC-Grafikkarte/html/product/100107963',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/Gainward/GeForce-RTX-5080-Phantom-GS-Grafikkarte/html/product/100105329',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/Gainward/GeForce-RTX-5080-Phantom-Grafikkarte/html/product/100105330',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/MSI/GeForce-RTX-5080-VENTUS-3X-OC-Grafikkarte/html/product/100109555',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/MSI/GeForce-RTX-5080-SUPRIM-LIQUID-SOC-Grafikkarte/html/product/100107946',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/ASUS/GeForce-RTX-5080-PRIME-OC-Grafikkarte/html/product/100108203',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/MSI/GeForce-RTX-5080-VENTUS-3X-OC-WHITE-Grafikkarte/html/product/100107967',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/ZOTAC/GeForce-RTX-5080-AMP-Extreme-INFINITY-Grafikkarte/html/product/100107996',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/GIGABYTE/GeForce-RTX-5080-AORUS-MASTER-ICE-16G-Grafikkarte/html/product/100108943',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/ASUS/GeForce-RTX-5080-PRIME-Grafikkarte/html/product/100108204',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/ASUS/GeForce-RTX-5080-TUF-GAMING-Grafikkarte/html/product/100108187',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/INNO3D/GeForce-RTX-5080-X3-Grafikkarte/html/product/100109396',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/ASUS/GeForce-RTX-5080-TUF-ROG-ASTRAL-GAMING-Grafikkarte/html/product/100108201',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/GIGABYTE/GeForce-RTX-5080-AORUS-MASTER-16G-Grafikkarte/html/product/100108944',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/GIGABYTE/GeForce-RTX-5080-AORUS-XTREME-WATERFORCE-16G-Grafikkarte/html/product/100108940',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/INNO3D/GeForce-RTX-5080-X3-OC-Grafikkarte/html/product/100109393',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5080',
      url: 'https://www.alternate.de/GIGABYTE/GeForce-RTX-5080-AORUS-XTREME-WATERFORCE-WB-16G-Grafikkarte/html/product/100108942',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/INNO3D/GeForce-RTX-5090-X3-Grafikkarte/html/product/100109380',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/MSI/GeForce-RTX-5090-32G-GAMING-TRIO-OC-Grafikkarte/html/product/100109565',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/MSI/GeForce-RTX-5090-32G-SUPRIM-LIQUID-SOC-Grafikkarte/html/product/100109560',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/MSI/GeForce-RTX-5090-32G-SUPRIM-SOC-Grafikkarte/html/product/100109563',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/ZOTAC/GeForce-RTX-5090-SOLID-OC-Grafikkarte/html/product/100110079',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/GIGABYTE/GeForce-RTX-5090-AORUS-MASTER-ICE-32G-Grafikkarte/html/product/100108931',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/MSI/GeForce-RTX-5090-32G-VENTUS-3X-OC-Grafikkarte/html/product/100109567',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/ASUS/GeForce-RTX-5090-ROG-ASTRAL-GAMING-Grafikkarte/html/product/100110142',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/ZOTAC/GeForce-RTX-5090-SOLID-Grafikkarte/html/product/100110077',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/GIGABYTE/GeForce-RTX-5090-AORUS-XTREME-WATERFORCE-WB-32G-Grafikkarte/html/product/100108929',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/MSI/GeForce-RTX-5090-32G-VANGUARD-SOC-LAUNCH-EDITION-Grafikkarte/html/product/100109564',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/ASUS/GeForce-RTX-5090-ROG-ASTRAL-LC-GAMING-Grafikkarte/html/product/100113293',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/ZOTAC/GeForce-RTX-5090-AMP-Extreme-INFINITY-Grafikkarte/html/product/100110080',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/ASUS/GeForce-RTX-5090-TUF-GAMING-OC-Grafikkarte/html/product/100110147',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/Gainward/GeForce-RTX-5090-Phantom-Grafikkarte/html/product/100109795',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/GIGABYTE/GeForce-RTX-5090-WINDFORCE-OC-32G-Grafikkarte/html/product/100108938',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/GIGABYTE/GeForce-RTX-5090-AORUS-XTREME-WATERFORCE-32G-Grafikkarte/html/product/100108927',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/GIGABYTE/GeForce-RTX-5090-GAMING-OC-32G-Grafikkarte/html/product/100108936',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/GIGABYTE/GeForce-RTX-5090-AORUS-MASTER-32G-Grafikkarte/html/product/100108932',
    },
    {
      brand: 'any',
      model: 'any',
      series: '5090',
      url: 'https://www.alternate.de/ASUS/GeForce-RTX-5090-TUF-GAMING-Grafikkarte/html/product/100110148',
    }
  ],
};
